// SPDX-FileCopyrightText: 2026 Yangtse Su <yangtsesu@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! S4's resampling criteria: agreement with an independent implementation, and
//! freedom from aliasing at a large reduction.
//!
//! Both are about `resample`, which is why it is public. The independent
//! implementation is ImageMagick's `-filter Lanczos -resize`, whose output is
//! committed as a fixture (`resample-lanczos-200.png`, generated by
//! `tests/fixtures/generate.py`); the aliasing test needs no reference at all,
//! because it compares against the exact area average of an analytic zone plate.

use std::path::{Path, PathBuf};

use pixlay_imaging::linear::{LinearRgb16, LinearRgba16};
use pixlay_imaging::{Region, Sampler, Source, resample, transfer};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../pixlay-cli/tests/fixtures/photos")
        .join(name)
}

/// Straight sRGB8 out of a linear buffer, for comparing against a reference PNG.
fn to_srgb8(image: &LinearRgb16) -> Vec<u8> {
    image.to_srgb8()
}

fn rmse(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len());
    let sum: f64 = a
        .iter()
        .zip(b)
        .map(|(x, y)| {
            let difference = f64::from(*x) - f64::from(*y);
            difference * difference
        })
        .sum();
    (sum / a.len() as f64).sqrt()
}

#[test]
fn a_large_reduction_matches_imagemagick_lanczos() {
    // 1600 -> 200 px is an 8x reduction: the case where a kernel that does not
    // widen reads one source pixel in eight and aliases the rest. ImageMagick's
    // Lanczos is the same filter computed by someone else, so the RMSE measures
    // agreement on the *implementation* (weights, edge handling, rounding), not
    // on a filter choice.
    let source = Source::decode(&fixture("resample-source.png")).expect("decodes");
    assert_eq!((source.width(), source.height()), (1600, 1200));
    let region = Region {
        display: (200.0, 150.0),
        texels: (0, 0, 200, 150),
    };
    let ours = resample(&source, region).over_white();
    let reference = Source::decode(&fixture("resample-lanczos-200.png")).expect("decodes");
    assert_eq!((reference.width(), reference.height()), (200, 150));
    let mut theirs = Vec::with_capacity(200 * 150 * 3);
    for y in 0..150 {
        for x in 0..200 {
            let pixel = reference.pixel(x, y);
            for sample in &pixel[..3] {
                theirs.push((sample >> 8) as u8);
            }
        }
    }

    let error = rmse(&to_srgb8(&ours), &theirs);
    // Measured 2026-09-21: 1.41 (max channel difference 29 at the hard-edged
    // square, where the two implementations' ringing differs). The threshold is
    // below the error a filter that does not widen its kernel produces — that one
    // is measured in `a_large_reduction_does_not_alias` against the exact average
    // — and above the disagreement two correct Lanczos implementations can have.
    assert!(error <= 3.0, "RMSE {error} against ImageMagick Lanczos");
    // A one-pixel shift or a transposed axis would show up here, not in the RMSE.
    let expected_level = |x: usize, y: usize| theirs[(y * 200 + x) * 3 + 1];
    let ours_level = to_srgb8(&ours)[(75 * 200 + 40) * 3 + 1];
    assert!(
        i32::from(ours_level).abs_diff(i32::from(expected_level(40, 75))) <= 8,
        "the reductions disagree at (40, 75): {ours_level}"
    );
}

/// An analytic zone plate: `0.5 + 0.5*sin(k*r^2)` in linear light.
///
/// Its local frequency grows with the radius (`k*r/pi` cycles per source pixel),
/// so a downsampled version has an inner disc that must be reproduced and an outer
/// ring where anything the sampler misses becomes moiré — the ideal answer there
/// is the *local average*, which this test computes exactly.
struct ZonePlate {
    size: u32,
    /// `k` in `sin(k*r^2)`, chosen so that an 8x reduction's Nyquist limit
    /// (`0.5/8 = 0.0625` cycles per source pixel) is crossed at r = 512 px:
    /// `k = 0.0625*pi/512`. Inside r = 256 the rings are below half the limit and
    /// must survive; outside r = 1024 they are past twice the limit and must
    /// average out.
    k: f64,
}

impl ZonePlate {
    fn new() -> Self {
        Self {
            size: 4096,
            k: 0.0625 * std::f64::consts::PI / 512.0,
        }
    }

    /// The linear-light value at one sample.
    fn linear(&self, x: u32, y: u32) -> f64 {
        let (dx, dy) = (f64::from(x) - 2048.0, f64::from(y) - 2048.0);
        0.5 + 0.5 * (self.k * (dx * dx + dy * dy)).sin()
    }

    /// The exact area average over the `factor x factor` block starting at
    /// `(x, y)`: the answer an ideal anti-aliasing filter gives.
    fn block_average(&self, x: u32, y: u32, factor: u32) -> f64 {
        let mut sum = 0.0;
        for dy in 0..factor {
            for dx in 0..factor {
                sum += self.linear(x + dx, y + dy);
            }
        }
        sum / f64::from(factor * factor)
    }
}

impl Sampler for ZonePlate {
    fn width(&self) -> u32 {
        self.size
    }

    fn height(&self) -> u32 {
        self.size
    }

    fn pixel(&self, x: u32, y: u32) -> [u16; 4] {
        // The pipeline reads sRGB samples, so the plate is encoded on the way in;
        // the comparison below is made in linear light on both sides, which is
        // where the local-averaging argument holds.
        let sample = transfer::to_fixed(transfer::inverse_transfer(self.linear(x, y)));
        [sample, sample, sample, u16::MAX]
    }
}

/// Mean absolute error of a buffer's green channel against `ideal`, over the
/// output texels whose *source* radius is inside `band` (in source pixels).
fn mean_error(
    ours: &LinearRgb16,
    ideal: impl Fn(usize, usize) -> f64,
    factor: u32,
    band: (f64, f64),
) -> (f64, usize) {
    let (mut sum, mut count) = (0.0, 0);
    for y in 0..ours.height() as usize {
        for x in 0..ours.width() as usize {
            let (dx, dy) = (
                (x as f64 + 0.5) * f64::from(factor) - 2048.0,
                (y as f64 + 0.5) * f64::from(factor) - 2048.0,
            );
            let radius = (dx * dx + dy * dy).sqrt();
            if radius < band.0 || radius > band.1 {
                continue;
            }
            sum += (transfer::from_fixed(ours.pixel(x as u32, y as u32)[1]) - ideal(x, y)).abs();
            count += 1;
        }
    }
    (sum / count.max(1) as f64, count)
}

#[test]
fn a_large_reduction_does_not_alias() {
    // 4096 -> 512 px, an 8x reduction, on content *designed* to alias: the outer
    // rings of a zone plate are past the reduced Nyquist limit, so a sampler that
    // reads one source pixel in eight turns them into moiré that was never in the
    // image.
    //
    // Both sides are compared against the exact area average, which is the ideal
    // answer:
    //
    //   * inside the passband (source radius < 256) the rings must be reproduced;
    //   * outside it (source radius > 1024) the answer is the local average, and
    //     only a widening kernel produces it.
    let plate = ZonePlate::new();
    let factor = 8u32;
    let out = plate.size / factor;
    let ours = resample(
        &plate,
        Region {
            display: (f64::from(out), f64::from(out)),
            texels: (0, 0, out as i32, out as i32),
        },
    )
    .over_white();
    let ideal =
        |x: usize, y: usize| plate.block_average(x as u32 * factor, y as u32 * factor, factor);
    // What a kernel that does not widen is equivalent to: one source sample per
    // output texel.
    let centre = factor / 2;
    let nearest =
        |x: usize, y: usize| plate.linear(x as u32 * factor + centre, y as u32 * factor + centre);
    let inner = (0.0, 256.0);
    let outer = (1024.0, f64::INFINITY);
    let (inner_ours, inner_count) = mean_error(&ours, ideal, factor, inner);
    let (inner_nearest, _) = mean_error(&ours, nearest, factor, inner);
    let (outer_ours, outer_count) = mean_error(&ours, ideal, factor, outer);
    let (outer_nearest, _) = mean_error(&ours, nearest, factor, outer);
    println!(
        "inner: ours {inner_ours:.4}, one-sample {inner_nearest:.4} ({inner_count} px); \
         outer: ours {outer_ours:.4}, one-sample {outer_nearest:.4} ({outer_count} px)"
    );

    // Both rings have to have something in them, or the numbers above are about
    // nothing.
    assert!(inner_count > 2_000, "only {inner_count} passband texels");
    assert!(outer_count > 50_000, "only {outer_count} stopband texels");

    // The passband survives: a filter that simply blurred everything would be
    // clean outside and empty inside.
    assert!(
        inner_ours <= 0.06,
        "the plate's inner rings are not reproduced: error {inner_ours}"
    );
    assert!(
        inner_nearest <= 0.06,
        "the ideal is not reachable in the passband: {inner_nearest}"
    );
    // Outside the passband the local average is the answer.
    assert!(
        outer_nearest > 0.05,
        "the baseline is not aliasing at all: {outer_nearest}"
    );
    assert!(
        outer_ours <= 0.35 * outer_nearest,
        "the widening kernel is not buying anything: ours {outer_ours}, one-sample {outer_nearest}"
    );
    // Measured 2026-09-21: ours 0.0202, one-sample-per-texel 0.3183 (210,676
    // texels), inner ring 0.0182 against 0.0191. The absolute cap is the measured
    // value with a 50% margin, and it is the separation from the baseline — 16x —
    // that makes the number mean "no aliasing" rather than "some".
    assert!(
        outer_ours <= 0.03,
        "aliasing outside the passband: {outer_ours}"
    );
}

#[test]
fn a_sixteen_bit_intermediate_is_not_an_eight_bit_one() {
    // The rule is "intermediate buffers are 16-bit, quantization happens at the
    // end" (`AGENTS.md`). What that buys is exactness: every one of the 256 sRGB
    // code values has its own linear value, and the round trip returns it
    // unchanged. An 8-bit linear intermediate cannot hold those values, and the
    // test demonstrates the difference rather than asserting the type.
    let codes: Vec<u8> = (0..=255).collect();
    let mut srgb = Vec::new();
    for code in &codes {
        srgb.extend_from_slice(&[*code, *code, *code]);
    }
    let buffer = LinearRgb16::from_srgb8(256, 1, &srgb);
    assert_eq!(buffer.to_srgb8(), srgb, "the 16-bit round trip is exact");

    // The same pipeline with an 8-bit *linear* intermediate: multiply the linear
    // value by 255 and round, which is what an 8-bit buffer does to it.
    let mut quantized = Vec::new();
    for code in &codes {
        let linear = transfer::from_fixed(transfer::srgb_to_linear(u16::from(*code) * 257));
        let linear8 = (linear * 255.0).round() / 255.0;
        quantized.push((transfer::inverse_transfer(linear8) * 255.0).round() as u8);
    }
    let broken = codes
        .iter()
        .zip(&quantized)
        .filter(|(want, got)| want != got)
        .count();
    assert!(
        broken > 16,
        "an 8-bit linear intermediate should lose codes, lost {broken}"
    );
}

#[test]
fn the_resampler_extends_the_edge_instead_of_fading_to_transparent() {
    // A covering fit puts the slot's boundary on the photo's boundary, so the
    // kernel reads past the last row and column. Extending them is what keeps the
    // slot from showing a transparent veil one pixel wide.
    let plate = ZonePlate::new();
    // The last 8 source pixels only: every tap of the first output texel falls
    // outside on the right except through the edge extension.
    let region = Region {
        display: (4096.0, 4096.0),
        texels: (4080, 0, 16, 16),
    };
    let out: LinearRgba16 = resample(&plate, region);
    assert_eq!((out.width(), out.height()), (16, 16));
    // Opacity survives: an edge that faded out would show alpha < 1 at the corner.
    for y in 0..16 {
        for x in 0..16 {
            assert_eq!(
                out.pixel(x, y)[3],
                u16::MAX,
                "the edge extension lost alpha at ({x}, {y})"
            );
        }
    }
}
