//! S9's preview criteria: a thumbnail is the pipeline's picture of a photo, at an
//! exact long edge.
//!
//! The independent check is the same one the resampler has: ImageMagick's Lanczos
//! reduction of the committed 1600x1200 source (`resample-lanczos-200.png`,
//! generated by `tests/fixtures/generate.py`). A preview that resampled
//! differently — or that went through a second color path — would miss that
//! reference, while a size assertion alone would not notice.
//!
//! The synthetic samplers carry the cases no fixture can: an exact ratio, an
//! upscale, a one-pixel pillarbox and an alpha channel.

use std::path::{Path, PathBuf};

use pixlay_imaging::{Sampler, Source, thumbnail};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../pixlay-cli/tests/fixtures/photos")
        .join(name)
}

fn rmse(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len());
    let sum: f64 = a
        .iter()
        .zip(b)
        .map(|(x, y)| {
            let difference = f64::from(*x) - f64::from(*y);
            difference * difference
        })
        .sum();
    (sum / a.len() as f64).sqrt()
}

/// A solid color, straight sRGB, at the file's own depth (`u16`, as `Source`
/// reports it).
struct Flat {
    width: u32,
    height: u32,
    color: [u16; 4],
}

impl Sampler for Flat {
    fn width(&self) -> u32 {
        self.width
    }

    fn height(&self) -> u32 {
        self.height
    }

    fn pixel(&self, _x: u32, _y: u32) -> [u16; 4] {
        self.color
    }
}

/// A horizontal ramp in sRGB: `x / (width - 1)` on every channel.
struct Ramp {
    width: u32,
    height: u32,
}

impl Sampler for Ramp {
    fn width(&self) -> u32 {
        self.width
    }

    fn height(&self) -> u32 {
        self.height
    }

    fn pixel(&self, x: u32, _y: u32) -> [u16; 4] {
        let value = (255.0 * f64::from(x) / f64::from(self.width - 1)).round() as u16;
        let sample = value * 257;
        [sample, sample, sample, u16::MAX]
    }
}

#[test]
fn a_thumbnail_matches_imagemagick_lanczos_at_the_same_size() {
    // The preview's whole job: 1600x1200 shown at a 200 px long edge is exactly the
    // region the resample tests measure, so the committed ImageMagick reduction is
    // the reference here too.
    let source = Source::decode(&fixture("resample-source.png")).expect("decodes");
    let thumb = thumbnail(&source, 200).expect("a preview");
    assert_eq!((thumb.width, thumb.height), (200, 150));

    let reference = Source::decode(&fixture("resample-lanczos-200.png")).expect("decodes");
    assert_eq!((reference.width(), reference.height()), (200, 150));
    let mut theirs = Vec::with_capacity(200 * 150 * 3);
    for y in 0..150 {
        for x in 0..200 {
            for sample in &reference.pixel(x, y)[..3] {
                theirs.push((sample >> 8) as u8);
            }
        }
    }

    // The same threshold `a_large_reduction_matches_imagemagick_lanczos` uses, and
    // for the same reason: 200/150 of a 1600x1200 source is the 8x reduction that
    // separates a widened kernel from a fixed one.
    let error = rmse(&thumb.pixels, &theirs);
    assert!(error <= 3.0, "RMSE {error} against ImageMagick Lanczos");
}

#[test]
fn the_long_edge_is_exact_and_the_ratio_is_kept() {
    let cases = [
        // (source size, requested long edge, expected size)
        ((1600, 1200), 200, (200, 150)),
        ((1600, 1200), 1, (1, 1)),
        ((600, 1200), 128, (64, 128)),
        ((640, 640), 100, (100, 100)),
        // A pillarbox: the short edge must not round to zero.
        ((10000, 1), 100, (100, 1)),
        // An upscale asks for more pixels than the source has — the picker's
        // fit-and-zoom preview does that — and the ratio still holds.
        ((100, 75), 400, (400, 300)),
        // Half away from zero, and at least one pixel.
        ((400, 200), 3, (3, 2)),
    ];
    for ((width, height), long_edge, expected) in cases {
        let source = Flat {
            width,
            height,
            color: [40000, 20000, 10000, u16::MAX],
        };
        let thumb = thumbnail(&source, long_edge).expect("a preview");
        assert_eq!(
            (thumb.width, thumb.height),
            expected,
            "{width}x{height} at {long_edge} px"
        );
        assert_eq!(thumb.pixels.len(), (expected.0 * expected.1 * 3) as usize);
        // The requested edge is exact on whichever axis is longer.
        assert_eq!(thumb.width.max(thumb.height), long_edge as i32);
    }

    // Zero has no picture to show and is refused rather than rounded up.
    let source = Flat {
        width: 100,
        height: 100,
        color: [0, 0, 0, u16::MAX],
    };
    assert!(thumbnail(&source, 0).is_err());
}

#[test]
fn a_flat_photo_comes_out_flat() {
    // A flat source must come out exactly flat: any structure here is a kernel or
    // an edge-handling bug (the same criterion the slot bitmaps are held to). The
    // value itself survives the linear-light round trip to within one level.
    let color = [30u8, 140, 200];
    let source = Flat {
        width: 640,
        height: 480,
        color: [
            u16::from(color[0]) * 257,
            u16::from(color[1]) * 257,
            u16::from(color[2]) * 257,
            u16::MAX,
        ],
    };
    let thumb = thumbnail(&source, 64).expect("a preview");
    assert_eq!((thumb.width, thumb.height), (64, 48));
    for (index, pixel) in thumb.pixels.as_chunks::<3>().0.iter().enumerate() {
        for channel in 0..3 {
            assert!(
                pixel[channel].abs_diff(color[channel]) <= 1,
                "pixel {index} is {pixel:?}, not {color:?}"
            );
        }
    }
}

#[test]
fn alpha_is_flattened_onto_white_like_a_slot() {
    // A fully transparent photo is not a hole in the picker: it is white, the same
    // rule the slots follow (`AGENTS.md`: an export is never transparent, and the
    // preview shows what the slot will show).
    let source = Flat {
        width: 40,
        height: 30,
        color: [0, 0, 0, 0],
    };
    let thumb = thumbnail(&source, 20).expect("a preview");
    assert_eq!((thumb.width, thumb.height), (20, 15));
    assert!(
        thumb.pixels.iter().all(|sample| *sample == 255),
        "a transparent photo must come out white"
    );
}

#[test]
fn a_preview_shows_the_whole_photo_rather_than_a_crop() {
    // The row-mean of a ramp is the ramp's own mean wherever it is sampled, so a
    // preview that cropped instead of shrinking would still pass a flat test but
    // fail this one: the left edge of the preview must be dark and the right edge
    // bright, with roughly the source's endpoints.
    let source = Ramp {
        width: 512,
        height: 256,
    };
    let thumb = thumbnail(&source, 128).expect("a preview");
    assert_eq!((thumb.width, thumb.height), (128, 64));
    let level = |x: i32, y: i32| -> u8 { thumb.pixels[((y * thumb.width + x) * 3) as usize] };
    let (left, right) = (level(0, 32), level(127, 32));
    assert!(left < 12, "left edge {left} is not the ramp's dark end");
    assert!(
        right > 243,
        "right edge {right} is not the ramp's bright end"
    );
    // Monotone across the row: an aliased or reversed axis bends back somewhere.
    for x in 1..128 {
        assert!(
            level(x, 32) >= level(x - 1, 32),
            "the ramp reverses at x = {x}"
        );
    }
}
