//! The font the text measurements run with.
//!
//! Glyph advances and line breaking are properties of a *font*: measured here,
//! `。，` costs two full ems with Noto Sans CJK and Pango punishes a line start with
//! `。`, but neither statement is about Pango alone — a machine whose only font
//! covers Latin would measure something else, and a clean chroot (`S8`) has no font
//! at all. So the tests pin one: `pixlay-cli`'s committed fixture font
//! `pixlay-test-sans.ttf` (a subset of Noto Sans CJK SC, SIL OFL, generated by
//! `generate.py` next to it; test assets are shared between crates this way, like
//! the photos `pixlay-imaging`'s tests use), reachable as `sans-serif` — the family
//! the renderer asks for.
//!
//! **Why a child process.** Fontconfig reads `FONTCONFIG_FILE` once, at its first
//! lookup, so the pin is a property of a *process* and not of a test; the
//! alternative is `unsafe { std::env::set_var }`, which this workspace's lints
//! forbid. `run_pinned` therefore starts this same test binary again with the
//! pinned environment and asserts the child passed — the `#[ignore]`d tests in
//! `measure.rs` only ever run there.

use std::path::{Path, PathBuf};
use std::process::Command;

/// The subset `generate.py` writes; also the name the tests' diagnostics use.
pub const FONT_FILE: &str = "pixlay-test-sans.otf";

/// The shared fixture directory: `pixlay-cli/tests/fixtures`, where the photos
/// `pixlay-imaging` renders and this font live.
fn font_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../pixlay-cli/tests/fixtures/fonts")
}

/// Runs the `#[ignore]`d tests whose name contains `filter` in a child process
/// with the pinned font, and asserts the child passed.
///
/// `expected` is the number of measurements the child must have executed: without
/// it a filter that matches nothing (a rename, a typo) would make this harness pass
/// while measuring nothing, which is exactly the vacuous pass `docs/STEPS.md`
/// hunts for.
pub fn run_pinned(filter: &str, expected: usize) {
    let font = font_dir().join(FONT_FILE);
    assert!(
        font.is_file(),
        "{} is missing; regenerate it with `python3 {}`",
        font.display(),
        font_dir().join("generate.py").display()
    );

    // Artifacts go to disk, never to tmpfs (`AGENTS.md`, measurement rules): the
    // font cache fontconfig builds is small but written per run.
    let scratch = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/var/tmp"))
        .join(format!("pixlay-text-tests/{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&scratch);
    std::fs::create_dir_all(scratch.join("cache")).expect("create scratch directory");

    // Only this file is listed, so fontconfig resolves `sans-serif` to the subset:
    // there is no other font to fall back to, and no per-machine font can leak in.
    let config = scratch.join("fonts.conf");
    std::fs::write(
        &config,
        format!(
            "<?xml version=\"1.0\"?>\n\
             <!DOCTYPE fontconfig SYSTEM \"urn:fontconfig:fonts.dtd\">\n\
             <fontconfig>\n\
             \x20 <dir>{fonts}</dir>\n\
             \x20 <cachedir>{cache}</cachedir>\n\
             </fontconfig>\n",
            fonts = font_dir().display(),
            cache = scratch.join("cache").display()
        ),
    )
    .expect("write fonts.conf");

    let exe = std::env::current_exe().expect("test binary path");
    let output = Command::new(exe)
        .args(["--ignored", filter, "--nocapture"])
        .env("FONTCONFIG_FILE", &config)
        .env("XDG_CACHE_HOME", &scratch)
        // The tests are English-only and must not read the user's locale.
        .env("LANG", "C")
        .env("LC_ALL", "C")
        .env("TZ", "UTC")
        .output()
        .expect("run the pinned child");

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "the pinned child failed ({}):\n{stdout}\n{stderr}",
        output.status
    );
    let passed = passed_count(&stdout);
    assert!(
        passed >= expected,
        "{passed} measurements ran, expected at least {expected}: the filter {filter:?} \
         no longer matches them, or one was deleted:\n{stdout}"
    );
}

/// Sums the `N passed` of every `test result:` line libtest printed.
fn passed_count(stdout: &str) -> usize {
    stdout
        .lines()
        .filter_map(|line| line.trim().strip_prefix("test result:"))
        .filter_map(|rest| rest.split_whitespace().nth(1))
        .filter_map(|count| count.parse::<usize>().ok())
        .sum()
}
