// SPDX-FileCopyrightText: 2026 Yangtse Su <yangtsesu@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! The sRGB profile every export carries.
//!
//! The pipeline produces sRGB (`docs/CONTRACT.md` §4.1) and an export is only
//! interpretable if it says so, so the profile is written into the file in the
//! same pass as the pixels. v1 pulls in no colour library — no `lcms2`, no
//! rendering intent of our own — so the bytes are built here from the IEC
//! 61966-2.1 colorimetry: the primaries and the D65 white point as chromaticities,
//! sRGB's piecewise transfer function, and the Bradford adaptation the profile
//! connection space demands.
//!
//! The shape is ICC v4 (class `mntr`, space `RGB `, PCS `XYZ `, `para` transfer
//! curves, `chad` recording the adaptation) — the shape lcms2 writes, so the
//! profile is a matrix-shaper display profile to every reader, and the media white
//! point is the D50 PCS illuminant.
//!
//! Nothing about these bytes depends on the clock or the machine: the profile is
//! derived from constants only, so two builds produce the same file bytes. The
//! profile id stays zero, which the specification allows and which is what keeps
//! that promise; the creation date is the fixed one below, because bytes 24..36
//! are a field a strict reader validates rather than free space (PIX-025, S15i).
//!
//! Measured 2026-09-21 against the sRGB profile committed inside
//! `pixlay-cli/tests/fixtures/photos/adobe-rgb-srgb.png` (written by ImageMagick
//! from colord's `sRGB.icc`, i.e. by an implementation that is not ours): the
//! colorants agree to 2.2e-4 and the transfer curve's parameters to one unit in
//! the last place of the profile's 15.16 fixed point (1.5e-5), and ImageMagick
//! converting a 1200 px export *from this profile to colord's sRGB* moves the
//! pixels by 0.0015/255 (RMSE 0.378 of 65535) — i.e. lcms2 reads the two as the
//! same colour space. See "S6 · measured".

use std::sync::OnceLock;

/// What the profile calls itself. This is the name a colour-managed application
/// shows, and it is the colorimetry the renderer means.
pub const DESCRIPTION: &str = "sRGB IEC61966-2.1";

/// The whole profile as it is embedded, built once per process.
pub fn srgb_profile() -> &'static [u8] {
    static PROFILE: OnceLock<Vec<u8>> = OnceLock::new();
    PROFILE.get_or_init(build)
}

const COPYRIGHT: &str = "Colorimetry of IEC 61966-2.1, generated by Pixlay";

/// The profile's creation date as the header's six `dateTimeNumber` fields — year,
/// month, day, hour, minute, second, UTC — which are header bytes 24..36 in that
/// order, each a big-endian `u16`.
///
/// **Fixed, not read from the clock**: two builds have to write the same bytes, and
/// a creation time is not a fact the product needs. What it must be is a *valid*
/// date — ICC.1:2010 §7.2.8 requires the field to hold the profile's creation time,
/// and §4.2 defines month as 1..=12 and day as 1..=31, so the zeroed field this
/// used to write is a date no reader can accept (zero is the documented sentinel
/// for the profile id at 84..100, and for nothing else). The value is the day the
/// encoder landed: S6, 2026-09-21 (`docs/CONTRACT.md` §8, "S6").
const CREATED: (u16, u16, u16, u16, u16, u16) = (2026, 9, 21, 0, 0, 0);

/// sRGB's primaries and white point as CIE 1931 chromaticities, and the transfer
/// function as an ICC parametric curve of type 3: `Y = (aX + b)^g` above `d`,
/// `Y = cX` below it.
const RED: (f64, f64) = (0.6400, 0.3300);
const GREEN: (f64, f64) = (0.3000, 0.6000);
const BLUE: (f64, f64) = (0.1500, 0.0600);
const WHITE: (f64, f64) = (0.3127, 0.3290);
const CURVE: (f64, f64, f64, f64, f64) = (2.4, 1.0 / 1.055, 0.055 / 1.055, 1.0 / 12.92, 0.04045);

/// The profile connection space's illuminant (ICC: D50).
const PCS_ILLUMINANT: [f64; 3] = [0.9642, 1.0, 0.8249];

/// The header's size, before tags.
const HEADER: usize = 128;

type Mat3 = [[f64; 3]; 3];

fn build() -> Vec<u8> {
    let matrix = srgb_to_pcs();
    let adaptation = bradford(xyz_of(WHITE.0, WHITE.1), PCS_ILLUMINANT);
    let chad: Vec<f64> = adaptation.iter().flatten().copied().collect();
    let mut tags: Vec<([u8; 4], Vec<u8>)> = vec![
        (*b"desc", text_tag(DESCRIPTION)),
        (*b"cprt", text_tag(COPYRIGHT)),
        (*b"wtpt", xyz_tag(PCS_ILLUMINANT)),
        (*b"chad", fixed_tag(b"sf32", &chad)),
        (*b"rXYZ", xyz_tag(column(matrix, 0))),
        (*b"gXYZ", xyz_tag(column(matrix, 1))),
        (*b"bXYZ", xyz_tag(column(matrix, 2))),
        (*b"rTRC", curve_tag()),
        (*b"gTRC", curve_tag()),
        (*b"bTRC", curve_tag()),
    ];
    // The specification orders the tag table by signature; readers accept any
    // order, and a canonical one is cheaper to compare than to explain.
    tags.sort_by_key(|(signature, _)| *signature);
    assemble(&tags)
}

/// Header, tag table and tag data, with 4-byte alignment throughout.
fn assemble(tags: &[([u8; 4], Vec<u8>)]) -> Vec<u8> {
    let table = HEADER + 4 + 12 * tags.len();
    let mut data: Vec<u8> = Vec::new();
    let mut entries: Vec<([u8; 4], u32, u32)> = Vec::with_capacity(tags.len());
    for (signature, bytes) in tags {
        entries.push((*signature, (table + data.len()) as u32, bytes.len() as u32));
        data.extend_from_slice(bytes);
        data.resize(data.len().next_multiple_of(4), 0);
    }

    let mut profile = vec![0u8; table];
    profile[128..132].copy_from_slice(&(tags.len() as u32).to_be_bytes());
    for (index, (signature, offset, size)) in entries.iter().enumerate() {
        let at = 132 + 12 * index;
        profile[at..at + 4].copy_from_slice(signature);
        profile[at + 4..at + 8].copy_from_slice(&offset.to_be_bytes());
        profile[at + 8..at + 12].copy_from_slice(&size.to_be_bytes());
    }
    profile.extend_from_slice(&data);

    let size = profile.len() as u32;
    profile[0..4].copy_from_slice(&size.to_be_bytes());
    // 4..8 CMM, 8..12 version: 4.3.
    profile[8..12].copy_from_slice(&0x0430_0000u32.to_be_bytes());
    profile[12..16].copy_from_slice(b"mntr");
    profile[16..20].copy_from_slice(b"RGB ");
    profile[20..24].copy_from_slice(b"XYZ ");
    // 24..36 the creation date: the six `dateTimeNumber` fields, as `u16`s.
    let (year, month, day, hour, minute, second) = CREATED;
    for (index, value) in [year, month, day, hour, minute, second].iter().enumerate() {
        let at = 24 + 2 * index;
        profile[at..at + 2].copy_from_slice(&value.to_be_bytes());
    }
    profile[36..40].copy_from_slice(b"acsp");
    // 40..44 platform, 44..48 flags, 48..56 device, 56..64 attributes: all zero
    // (unknown / not applicable / no device).
    // 64..68 the rendering intent: 0 = perceptual, which is what a bitmap is
    // rendered for and what every reader assumes.
    for (index, value) in PCS_ILLUMINANT.iter().enumerate() {
        let at = 68 + 4 * index;
        profile[at..at + 4].copy_from_slice(&fixed(*value));
    }
    profile[80..84].copy_from_slice(b"pixl");
    // 84..100 the profile id and 100..128 the reserved bytes stay zero.
    profile
}

/// `mluc` (multi-localized Unicode): one `en-US` record.
fn text_tag(text: &str) -> Vec<u8> {
    let utf16: Vec<u8> = text.encode_utf16().flat_map(u16::to_be_bytes).collect();
    let mut tag = Vec::with_capacity(28 + utf16.len());
    tag.extend_from_slice(b"mluc");
    tag.extend_from_slice(&0u32.to_be_bytes());
    tag.extend_from_slice(&1u32.to_be_bytes());
    tag.extend_from_slice(&12u32.to_be_bytes());
    tag.extend_from_slice(b"enUS");
    tag.extend_from_slice(&(utf16.len() as u32).to_be_bytes());
    tag.extend_from_slice(&28u32.to_be_bytes());
    tag.extend_from_slice(&utf16);
    tag
}

/// `XYZ `: one colour, as three 15.16 fixed point numbers.
fn xyz_tag(value: [f64; 3]) -> Vec<u8> {
    fixed_tag(b"XYZ ", &value)
}

/// `para`: the transfer curve, function type 3 and its five parameters.
fn curve_tag() -> Vec<u8> {
    let mut tag = Vec::with_capacity(32);
    tag.extend_from_slice(b"para");
    tag.extend_from_slice(&0u32.to_be_bytes());
    tag.extend_from_slice(&3u16.to_be_bytes());
    tag.extend_from_slice(&0u16.to_be_bytes());
    for value in [CURVE.0, CURVE.1, CURVE.2, CURVE.3, CURVE.4] {
        tag.extend_from_slice(&fixed(value));
    }
    tag
}

/// A tag whose payload is a run of 15.16 fixed point numbers.
fn fixed_tag(signature: &[u8; 4], values: &[f64]) -> Vec<u8> {
    let mut tag = Vec::with_capacity(8 + 4 * values.len());
    tag.extend_from_slice(signature);
    tag.extend_from_slice(&0u32.to_be_bytes());
    for value in values {
        tag.extend_from_slice(&fixed(*value));
    }
    tag
}

/// `s15Fixed16Number`: 15 bits of integer and 16 of fraction, big endian.
fn fixed(value: f64) -> [u8; 4] {
    ((value * 65_536.0).round() as i32).to_be_bytes()
}

/// The matrix that takes sRGB's linear values to the D50-adapted PCS, i.e. the
/// profile's `rXYZ` / `gXYZ` / `bXYZ`.
///
/// Derived, not copied: the primaries and the white point define it, and the
/// derivation is what makes the profile checkable against another
/// implementation's (see the module docs).
fn srgb_to_pcs() -> Mat3 {
    let primaries = [
        xyz_of(RED.0, RED.1),
        xyz_of(GREEN.0, GREEN.1),
        xyz_of(BLUE.0, BLUE.1),
    ];
    let rgb_to_xyz: Mat3 = [
        [primaries[0][0], primaries[1][0], primaries[2][0]],
        [primaries[0][1], primaries[1][1], primaries[2][1]],
        [primaries[0][2], primaries[1][2], primaries[2][2]],
    ];
    // Scale the channels so that a linear (1, 1, 1) lands on the white point.
    let white = xyz_of(WHITE.0, WHITE.1);
    let scale = mul_vec(invert(rgb_to_xyz), white);
    let d65: Mat3 = [
        [
            rgb_to_xyz[0][0] * scale[0],
            rgb_to_xyz[0][1] * scale[1],
            rgb_to_xyz[0][2] * scale[2],
        ],
        [
            rgb_to_xyz[1][0] * scale[0],
            rgb_to_xyz[1][1] * scale[1],
            rgb_to_xyz[1][2] * scale[2],
        ],
        [
            rgb_to_xyz[2][0] * scale[0],
            rgb_to_xyz[2][1] * scale[1],
            rgb_to_xyz[2][2] * scale[2],
        ],
    ];
    mul(bradford(white, PCS_ILLUMINANT), d65)
}

/// The Bradford adaptation that takes `from`'s white to `to`'s.
fn bradford(from: [f64; 3], to: [f64; 3]) -> Mat3 {
    /// The Bradford cone response matrix, the one the ICC recommends.
    const BRADFORD: Mat3 = [
        [0.8951, 0.2664, -0.1614],
        [-0.7502, 1.7135, 0.0367],
        [0.0389, -0.0685, 1.0296],
    ];
    let source = mul_vec(BRADFORD, from);
    let target = mul_vec(BRADFORD, to);
    let scaling: Mat3 = [
        [target[0] / source[0], 0.0, 0.0],
        [0.0, target[1] / source[1], 0.0],
        [0.0, 0.0, target[2] / source[2]],
    ];
    mul(mul(invert(BRADFORD), scaling), BRADFORD)
}

/// CIE XYZ of a chromaticity, normalized so that `Y = 1`.
fn xyz_of(x: f64, y: f64) -> [f64; 3] {
    [x / y, 1.0, (1.0 - x - y) / y]
}

fn column(matrix: Mat3, index: usize) -> [f64; 3] {
    [matrix[0][index], matrix[1][index], matrix[2][index]]
}

fn mul(a: Mat3, b: Mat3) -> Mat3 {
    let mut out = [[0.0; 3]; 3];
    for (i, row) in out.iter_mut().enumerate() {
        for (j, cell) in row.iter_mut().enumerate() {
            *cell = (0..3).map(|k| a[i][k] * b[k][j]).sum();
        }
    }
    out
}

fn mul_vec(matrix: Mat3, vector: [f64; 3]) -> [f64; 3] {
    let mut out = [0.0; 3];
    for (i, value) in out.iter_mut().enumerate() {
        *value = (0..3).map(|k| matrix[i][k] * vector[k]).sum();
    }
    out
}

/// The inverse of a 3x3 matrix, by its adjugate. The matrices here are the colour
/// transforms above — none of them is singular, and `det` is commented rather
/// than guarded because a guard would only hide an arithmetic mistake.
fn invert(matrix: Mat3) -> Mat3 {
    let m = matrix;
    let det = m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
        - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
        + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]);
    let s = 1.0 / det;
    [
        [
            (m[1][1] * m[2][2] - m[1][2] * m[2][1]) * s,
            (m[0][2] * m[2][1] - m[0][1] * m[2][2]) * s,
            (m[0][1] * m[1][2] - m[0][2] * m[1][1]) * s,
        ],
        [
            (m[1][2] * m[2][0] - m[1][0] * m[2][2]) * s,
            (m[0][0] * m[2][2] - m[0][2] * m[2][0]) * s,
            (m[0][2] * m[1][0] - m[0][0] * m[1][2]) * s,
        ],
        [
            (m[1][0] * m[2][1] - m[1][1] * m[2][0]) * s,
            (m[0][1] * m[2][0] - m[0][0] * m[2][1]) * s,
            (m[0][0] * m[1][1] - m[0][1] * m[1][0]) * s,
        ],
    ]
}
